const LOGIN_LOADING = "LOGIN_LOADING";
const LOGIN_ERROR = "LOGIN_ERROR";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";

const REGISTER_LOADING = "REGISTER_LOADING";
const REGISTER_ERROR = "REGISTER_ERROR";
const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export {
  LOGIN_ERROR,
  LOGIN_LOADING,
  LOGIN_SUCCESS,
  REGISTER_ERROR,
  REGISTER_LOADING,
  REGISTER_SUCCESS,
  LOGOUT_SUCCESS
};
