const GET_DATA_LOADING = "GET_DATA_lOADING";
const GET_DATA_ERROR = "GET_DATA_ERROR";
const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";

const POST_DATA_LOADING = "POST_DATA_lOADING";
const POST_DATA_ERROR = "POST_DATA_ERROR";
const POST_DATA_SUCCESS = "POST_DATA_SUCCESS";

export {
  GET_DATA_ERROR,
  GET_DATA_LOADING,
  GET_DATA_SUCCESS,
  POST_DATA_ERROR,
  POST_DATA_LOADING,
  POST_DATA_SUCCESS
};
