const ADD_TODO_SUCCESS = "ADD_TODO_SUCCESS";
const ADD_TODO_LOADING = "ADD_TODO_LOADING";
const ADD_TODO_ERROR = "ADD_TODO_ERROR";

const DELETE_TODO_SUCCESS = "DELETE_TODO_SUCCESS";
const DELETE_TODO_LOADING = "DELETE_TODO_LOADING";
const DELETE_TODO_ERROR = "DELETE_TODO_ERROR";

const UPDATE_TODO_SUCCESS = "UPDATE_TODO_SUCCESS";
const UPDATE_TODO_LOADING = "UPDATE_TODO_LOADING";
const UPDATE_TODO_ERROR = "UPDATE_TODO_ERROR";

const GET_TODO_SUCCESS = "GET_TODO_SUCCESS";
const GET_TODO_LOADING = "GET_TODO_LOADING";
const GET_TODO_ERROR = "GET_TODO_ERROR";

const GET_SINGLE_TODO = "GET_SINGLE_TODO";

export {
  ADD_TODO_ERROR,
  ADD_TODO_LOADING,
  ADD_TODO_SUCCESS,
  GET_TODO_ERROR,
  GET_TODO_SUCCESS,
  GET_TODO_LOADING,
  UPDATE_TODO_ERROR,
  UPDATE_TODO_LOADING,
  UPDATE_TODO_SUCCESS,
  DELETE_TODO_ERROR,
  DELETE_TODO_LOADING,
  DELETE_TODO_SUCCESS,
  GET_SINGLE_TODO
};
